FROM nvidia/cuda:9.0-devel-ubuntu16.04
LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"

ENV CUDNN_VERSION 7.6.4.38
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    libcudnn7=$CUDNN_VERSION-1+cuda9.0 \
libcudnn7-dev=$CUDNN_VERSION-1+cuda9.0 \
&& \
    apt-mark hold libcudnn7 && \
    rm -rf /var/lib/apt/lists/*

# Install additional packages (as root user)
RUN apt-get update && apt-get install -y \
    sudo \
    vim 

ARG GROUP_ID=1012
ARG USER_ID=1012

RUN groupadd -g ${GROUP_ID} docker &&\
    useradd -l -u ${USER_ID} -g docker docker &&\
    echo "docker:docker" | chpasswd &&\
    adduser docker sudo &&\
    install -d -m 0755 -o docker -g docker /home/docker

USER docker

